#!/bin/sh

uci batch <<EOF
set system.@system[0].timezone='CST-8'
set system.@system[0].zonename='Asia/Shanghai'
EOF

uci commit system
/etc/init.d/system restart
rm -f /etc/uci-defaults/80-system-config
