#!/bin/sh

uci batch <<EOF
set network.device_eth0=device
set network.device_eth0.name='eth0'
set network.device_eth0.macaddr='aa:b0:fe:60:db:ec'

set network.wan=interface
set network.wan.device='eth0'
set network.wan.proto='static'
set network.wan.ipaddr='192.168.1.11'
set network.wan.netmask='255.255.255.0'
set network.wan.gateway='192.168.1.1'
add_list network.wan.dns='223.5.5.5'
EOF

commit network

/etc/init.d/network restart

rm -f /etc/uci-defaults/80-wan-config
