#!/bin/sh

uci batch <<EOF
set mihomo.config.enabled='1'

set mihomo.proxy.tcp_transparent_proxy_mode='tun'
set mihomo.proxy.bypass_china_mainland_ip='1'

set mihomo.subscription.name='uk'
set mihomo.subscription.url='https://sub.unkind.uk'

set mihomo.mixin.authentication='0'
set mihomo.mixin.fake_ip_cache='0'
set mihomo.mixin.dns_doh_prefer_http3='1'
set mihomo.mixin.geoip_format='mmdb'
set mihomo.mixin.geox_auto_update='1'
et mihomo.mixin.api_secret='0112358'
EOF

uci commit mihomo

/etc/init.d/mihomo restart

rm -f /etc/uci-defaults/86-mihomo-config
