name: Delete All Workflows, Releases, and Tags

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Confirm deletion (type YES to proceed)'
        required: true

permissions:
  contents: write
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史和标签

      - name: Check confirmation
        if: github.event.inputs.confirm != 'YES'
        run: |
          echo "Deletion not confirmed. Please type 'YES' to proceed."
          exit 1

      - name: Delete All Workflows
        env:
          GH_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          # List and delete workflow runs
          workflows=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs | jq -r '.workflow_runs[].id')
          for run in $workflows; do
            gh api -X DELETE /repos/${{ github.repository }}/actions/runs/$run || true
          done

      - name: Delete All Releases
        env:
          GH_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          # List and delete releases
          releases=$(gh release list -R ${{ github.repository }} | awk '{print $1}')
          for release in $releases; do
            gh release delete "$release" -R ${{ github.repository }} -y || true
          done

      - name: Delete All Local and Remote Tags
        env:
          GH_TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: |
          # 删除本地标签
          git tag | xargs -n 1 git tag -d

          # 删除远程标签
          git push origin --delete $(git tag)

          # 使用 GitHub CLI 删除远程标签
          tags=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/tags | jq -r '.[].name')
          for tag in $tags; do
            gh api -X DELETE /repos/${{ github.repository }}/git/refs/tags/$tag || true
          done

          # 再次确认删除所有远程标签
          git push origin --tags --force
