#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-22.04

    steps:
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@master
      with:
        timeZone: UTC+8
        format: 'YYYY-MM-DD-HH-mm-ss'
    - name: Usage
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        echo $TIME
